GET http://140.238.54.136/api/province?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTQwLjIzOC41NC4xMzYvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2ODM3MzEzODYsImV4cCI6MTY4MzczMTk4NiwibmJmIjoxNjgzNzMxMzg2LCJqdGkiOiJPY29nZHhVQ2FxWTRRSkNpIiwic3ViIjoiNTg5ZGY4MDBjZGYyNGZmMWEwM2MwMGYyMTQ4OWYwMDciLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.BrAoPvPHvJ9oFXbJ2xiBhyvHX4sI_3_VlI4vuMmUA2g
Content-Type:application/json

