GET http://140.238.54.136/api/district?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTQwLjIzOC41NC4xMzYvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2ODQ3ODU0MTQsImV4cCI6MTY4NDc4NjAxNCwibmJmIjoxNjg0Nzg1NDE0LCJqdGkiOiI0dVR1d2dvbmFoWHlJY1BjIiwic3ViIjoiNTg5ZGY4MDBjZGYyNGZmMWEwM2MwMGYyMTQ4OWYwMDciLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.MpSzc-lBonZhIv2tXr-B5r5uv_huCq4nEweJtSQNYB0
Content-Type:application/json

{
  "provinceID": 250
}
